let mongoose = require('mongoose');
let Order = mongoose.Schema({
  
    id: {type:Number,require:true},
    admin_graphql_api_id: {type:String,require:false},
    app_id: {type:Number,require:true},
    browser_ip: {type:String,require:false},
    buyer_accepts_marketing: {type:Boolean,require:false},
    cancel_reason: {type:String,require:false},
    cancelled_at: {type:String,require:false},
    cart_token: {type:String,require:false},
    checkout_id: {type:String,require:false},
    checkout_token: {type:String,require:false},
    client_details: {type:String,require:false},
    closed_at: {type:String,require:false},
    confirmed: {type:Boolean,require:false},
    contact_email: {type:String,require:false},
    created_at: {type:String,require:false},
    currency: {type:String,require:false},
    current_subtotal_price: {type:String,require:false},
    current_subtotal_price_set: {type:Object,require:false},
    current_total_discounts: {type:String,require:false},
    current_total_discounts_set: {type:Object,require:false},
    current_total_duties_set: {type:String,require:false},
    current_total_price: {type:String,require:false},
    current_total_price_set: {type:Object,require:false},
    current_total_tax: {type:String,require:false},
    current_total_tax_set: {type:Object,require:false},
    customer_locale: {type:String,require:false},
    device_id: {type:String,require:false},
    discount_codes: {type:Array,require:false},
    email:{type:String,require:false},
    estimated_taxes: {type:Boolean,require:false},
    financial_status: {type:String,require:false},
    fulfillment_status: {type:String,require:false},
    gateway: {type:String,require:false},
    landing_site: {type:String,require:false},
    landing_site_ref:{type:String,require:false},
    location_id: {type:String,require:false},
    name: {type:String,require:false},
    note: {type:String,require:false},
    note_attributes:{type:Array,require:false},
    number: {type:Number,require:false},
    order_number: {type:String,require:false},
    order_status_url: {type:String,require:false},
    original_total_duties_set: {type:String,require:false},
    payment_gateway_names: {type:Array,require:false},
    phone: {type:String,require:false},
    presentment_currency: {type:String,require:false},
    processed_at: {type:String,require:false},
    processing_method: {type:String,require:false},
    reference: {type:String,require:false},
    referring_site: {type:String,require:false},
    source_identifier: {type:String,require:false},
    source_name: {type:String,require:false},
    source_url: {type:String,require:false},
    subtotal_price: {type:String,require:false},
    subtotal_price_set: {type:Object,require:false},
    tags: {type:String,require:false},
    tax_lines: {type:Array,require:false},
    taxes_included: {type:Boolean,require:false},
    test: {type:String,require:false},
    token: {type:String,require:false},
    total_discounts: {type:String,require:false},
    total_discounts_set: {type:Object,require:false},
    total_line_items_price: {type:String,require:false},
    total_line_items_price_set: {type:Object,require:false},
    total_outstanding: {type:String,require:false},
    total_price: {type:String,require:false},
    total_price_set: {type:Object,require:false},
    total_price_usd: {type:String,require:false},
    total_shipping_price_set: {type:Object,require:false},
    total_tax: {type:String,require:false},
    total_tax_set: {type:Object,require:false},
    total_tip_received: {type:String,require:false},
    total_weight: {type:Number,require:false},
    updated_at: {type:String,require:false},
    user_id: {type:String,require:false},
    billing_address: {type:Object,require:false},
    customer: {type:Object,require:false},
    discount_applications: {type:Array,require:false},
    fulfillments: {type:Array,require:false},
    line_items: {type:Array,require:false},
    payment_details: {type:String,require:false},
    refunds: {type:Array,require:false},
    shipping_address: {type:Object,require:false},
    shipping_lines: {type:Array,require:false}

  });

  module.exports = Order = mongoose.model('Order',Order);